version: '3.8'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    ports:
      - 80:80
  
  client:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    volumes:
      - ./client/:/client/
    ports:
      - 5173:5173
