version: '3.8'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app/:/backend/app/
    ports:
      - 8080:8080
  
  my-react-app:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    volumes:
      - ./my-react-app/src/:/my-react-app/src/
      - ./my-react-app/public/:/my-react-app/public/
    ports:
      - 5173:5173
